# Introduction

## Control and monitoring of tephritid fruit flies

Biological (pest) invasions are incursions of incipient populations of plants or animals that are non-native to a given region.^[Note that, for this work, the term *population* will be used to mean a group of animals living together in a group. This is to be distinguished from the statistical use of the term.] Such invasions can have high economic significance when the invading species is considered a *pest* (i.e., harmful to human concerns). Amid the ongoing globalisation of trade, the salience of biological invasions is increasing around the world. Invasions pose severe economic and environmental risks. On the economic side, they may threaten "wholesale loss of agricultural, forestry, and fishery resources" (@mack2000). On the environmental side, they may threaten to disrupt native ecological processes -- e.g. by threatening the extinction of endangered natives, and creating globally homogenous, "cosmopolitan" ecological systems (Ibid.).

Tephritid fruit flies (*Diptera tephritidae*) are a genus of insects of particularly high economic significance. Species in this genus have the potential to destroy a wide variety of horticultural produce in large amounts. Females lay eggs in plant tissue (often fruits) which is then destroyed in the process of their development. The potential economic costs of successful fruit fly invasions in Australia are estimated to be in the hundreds of millions of dollars (@suckling2016, @hancock2000), due to potential crop losses; the cost of labour and materials associated with eradication and suppression; and knock-on effects to agricultural produce as a consequence of pesticide usage required to manage fruit fly populations (@suckling2016).

Some locations in Australia and the USA are internationally recognised exclusion zones for some species of fruit fly. In some of these places *spot infestations* of the relevant fly species can be common (@meats2005). Spot infestations are small invasions, usually met with efforts to eradicate. Eradication methods include spraying of pesticides and release of sterile insects that disrupt the flies' breeding cycle. Currently, it is widespread practice that inference of absence for such invasions is informal. In particular, pest absence is declared according to rules of thumb (Ibid.). These rules are in the form of **zero-catch criteria**. The idea is that, if zero flies are detected for some pre-specified length of time (the zero-catch criterion) we may infer with confidence, and therefore declare, that they have been eradicated from the region (see chapter 2). 

There are issues with the zero-catch criteria currently used. Firstly, they are only minimally sensitive to variability between situations. For example, outbreaks in two locations with the same temperatures will have the same zero-catch criteria, even though they may differ in other significant ways. Secondly, they do not explicitly or transparently take into account the low sensitivity of fruit fly traps, which has been the subject of some study (see chapter 2). Thirdly, they are based on a simplified model of fruit fly biology which does not account for variation in development times (both within and between fly populations).

The primary goal of the present work is to develop a rigorous statistical framework for inferring pest absence after a suspected outbreak. The hope is that such a framework can be useful (a) to evaluate existing zero-catch criteria, and (b) to develop improved zero-catch criteria for inferring pest absence in future outbreaks. A secondary goal of the framework is to provide situation-specific estimates of the probability of eradication. These may be of significant utility to policymakers, given the increasing frequency with which regulators -- both in Australia and in other major agricultural producing countries -- must weigh the costs of efforts to eradicate pests probabilistically against the costs of successful biological invasion.

The method I propose involves spatially explicit, agent-based modelling of the relevant fruit fly population. This proposal is inspired by similar recent works using Bayesian models to infer the probability of absence for fire ants in Queensland, and for red foxes in Tasmania (see chapter 2).

## Outline

I begin this work in chapter 2 with a review of relevant literature. In particular, I discuss two bodies of research. The first is on the existing work that conducts quantitative analysis of zero-catch criteria for tephritid fruit flies. I explain zero-catch criteria in greater detail, and then discuss some ways in which they have been analysed and evaluated in ecology literature. The second body of literature concerns the use of Bayesian models for inferring the probability of pest absence. Two example cases from the literature are discussed as inspiration for the model developed in the present work. In chapter 3, I develop, and justify, a framework for modelling tephritid fruit fly invasions. Model details are discussed at an abstract level. The focus of this chapter is to present a skeleton of the method. I.e., the basic structure of the model, and core quantities of interest, are discussed. But the model is not fully specified or fit to data. Finally, in chapter 4, I apply the methodology to the specific case of Mediterranean fruit fly, a tephritid species of particularly high economic significance in the USA and Australia. A joint prior distribution is defined over the parameters of the model, and inference is performed to evaluate and derive zero-catch criteria for a hypothetical case. Chapter 5 concludes with a discussion of the findings and their implications for future research and policy.