# General framework proposal {#ch3}

## Introduction

In this chapter, I describe a general probabilistic model of an ecological system. The size, location, and number of captures, for a biological population, are explicitly modelled. The model is agent-based, as the properties of individual flies (namely their locations) are explicitly represented as latent (i.e. unobservable) variables. It is assumed that the data given are a number of captures (or, alternatively, sightings or detections), and that we wish to infer posterior distributions for the parameters governing size and/or locations. The structure of the model is explained, along with core parameters. Specific prior distributions are not set here, as prior distributions should depend on the species of fly under consideration. In chapter 4, a case study is performed, where the prior distributions and likelihood are specified more precisely.

## Why make the model spatially explicit?

The value of including a spatial component in the model may be questioned. This is relatively unusual in standard approaches (see, e.g., @mcardle1990). It is typical, instead, to assume that each fly has identical probability of being detected (captured). However, incorporating the spatial component allows us to leverage a useful source of prior information about trap efficacy. There exists a moderately large literature of **release-recapture** studies for various species of fruit fly (see @andress2013 for a review). Release recapture studies give us two kinds of data -- on one hand, we get the total proportion of flies recaptured; on the other hand, we also get the mean proportion of flies captured **per trap**, given distance between that trap and the release point. The first kind of data can be useful when the experimental setting is similar to the real-world setting for which we want to perform inference. This will be approximately the case when the types of traps, their number, and the spacing between them, are the same. However, this will often not be the case. In particular, studies vary significantly in the types and number of traps used. For example, @lance1994 used Jackson traps spaced 1.6 km apart, as is standard in California. Meanwhile, @ms2007 used Lynfield traps, spaced 0.4 km apart, as is standard in Adelaide. Further, we may wish to infer eradication of pest populations in trapping systems that are genuinely novel or untested. For example, after an outbreak has occurred, and eradication measures have been stopped, it is common to set up supplementary trapping units to intensify monitoring and increase the likelihood of detecting flies, conditional on their presence in the area (@supptraps). 

## Structure of the model

At the most basic level, I propose to define a joint distribution over (a) the number of flies in a population, (b) the location of each fly, and (c) whether or not any flies were detected (i.e. caught in traps). Defining notation, at each time point $t$, we must define a joint distribution over (a) the number of flies $N_t$, (b) the $N_t \times 2$ matrix of fly locations $\mathbf L_t$, and (c) an indicator variable $y_t$ which is 1 if any fly was caught at time $t$.^[It is assumed that the frequency of time points $t$ corresponds to the frequency at which surveillance traps are checked.] I.e., the model is in essence a joint distribution $p(\{N_t, \mathbf L_t, y_t\}_{t=1}^T)$. Recall that our goal is to evaluate zero-catch criteria for declaring eradication. Therefore, to evaluate zero-catch criteria, we want to infer $\Pr(N_T = 0 \mid \mathbf \{y_t\}_{t=1}^T = \mathbf 0_T)$, where $T$ is the established zero-catch criteria, based on degree day calculations. Call this quantity **the probability of eradication conditional on no detection**. To derive new zero-catch criteria, we want to find the smallest $T$ such that $\Pr(N_T = 0 \mid \{y_t\}_{t=1}^T = \mathbf 0_T) < 1-\alpha$, for some threshold $\alpha$. Here, $\alpha$ represents our risk tolerance. Call this quantity **the time to eradication**.

A Bayesian framework is assumed for inference. As such, to infer the above quantities, we must specify a joint **prior** distribution over $\{N_t, \mathbf L_t\}$, and a likelihood, i.e. a distribution for $\mathbf y \mid \{N_t, \mathbf L_t\}_{t=1}^T$. Instead of defining a joint prior directly on $\mathbf N = \{N_t\}_{t=1}^T$, I define a prior distribution over the parameters that govern the process by which the population grows or decays over time. As such, an assumed stochastic growth model structures the prior over $\mathbf N$.

### Population size

As mentioned above, a prior distribution must be set for the population size $N_t$ at each time point $t \in \{1, \ldots, T\}$. A natural way to do this is to define a stochastic model of the population's change. Explicitly, I recommend to define a prior over $N_1$ directly. Then, for each $t \in \{1,2, \ldots, T\}$, define a prior on $N_t$, conditional on the previous values $\{N_i\}_{i=1}^{t-1}$, as well as parameters governing the growth. A simple example, which I employ in chapter 4, is the Poisson branching process with exponential growth or decay. This is a model of the form
$$
N_t \mid \{N_{t-1}, R_t\} \sim \operatorname{Poisson}(N_{t-1} \exp \{R_t\}),
$$
where a continuous prior distribution is defined over the $R_t$ terms, which may have support over the whole real line.^[Alternatively, the logistic growth model, with an additional "carrying capacity" parameter, could be used.] This model has the attractive property that, when we condition on $\{R_t\}_{t=1}^T$ but marginalise out $\{N_t\}_{t=1}^{T-1}$, $N_T$ has mean $\mathrm E(N_1) \exp \left\{ \sum_{t=1}^T R_t \right\}$.^[Note, however that $N_T \mid \{R_t\}_{t=1}^T$ is not Poisson distributed, and has variance strictly larger than its mean.] This is attractive because the exponential growth model is popular in biology and ecology. Given this, in many cases, it should be relatively simple to set informative prior hyperparameters for the latent variable $R_t$. We might do this through expert elicitation, or through review of the relevant literature, in which population change may already be expressed in terms of growth rates.^[For example, see @papadopoulos2002.]

It may be worth noting that we could choose to factor in covariate information for the growth process. For example, for a given pest species, we might understand the growth of populations over time as a function of weather or rainfall. 

It may also be worth noting that there are no a priori assumptions on the population dynamics for the growth model. In principle, it should be simple to "plug in" elaborate growth models. For example, the models of @lux2018 or @manoukis2014 could be used to generate independent random draws from the population of Medfly. In this way, they can structure our prior over the population size. In this case, inference would proceed simply as in the case I outline here. This is outside the scope of this thesis, and I do not explore it further. However, this highlights key benefits of the modelling approach taken here, namely its flexibility and modularity.

### Fly locations

As mentioned previously, I propose to explicitly model the location of each fly. As a consequence, at each time $t$, a prior distribution must be set on each of the $N_t$ flies. Accounting for prior beliefs about the location of each fly introduces substantial complexity to the model. However, this can be simplified significantly, as I hope to demonstrate here. 

Note that, in typical situations, we will not be interested in inferring the posterior distributions of fly locations. As such, this is a nuisance parameter.

I first discuss the option of setting an uninformative prior. Setting an uninformative prior is fairly straightforward for this problem. In particular, we might assume that, beyond a certain distance from the outbreak centre (say, 1 km) any existing population of Medfly is distinct from the population of interest. Therefore, we might set the prior distribution for the population location to be uniform on the surface of a disc with (e.g.) 1 km radius around the outbreak centre. 

Although an uninformative prior is relatively straightforward to set, it is most likely not advisable in specific applications. Firstly, when an outbreak is suspected, it is typical that information about location is available. On one hand, fruit flies are heavily dependent on the availability of suitable fruit trees for survival and reproduction. Therefore, someone with local area knowledge will be able to determine the most likely locations for an existing population. On the other hand, if an outbreak is known or suspected, then flies must have been detected somewhere. Most likely, the locations of these detections will be known to the analyst. When the fly species has low dispersal distances (as e.g. medfly does) these detection locations are highly informative. Therefore, an informative prior, utilising this information, formally or informally, is recommended.

It is assumed the flies are typically clustered in space. This may be justifiable in practice. For a small, seed population, a population with low density will die out due to the Allee effect.^[In biology and ecology, the Allee effect is the effect of population density on individual fitness. For example, when the population density is low, it may become more difficult to find a viable mate, and individuals may have greater exposure to risk of predation. See @stephens1999.] However, when this assumption is not realistic, an alternative prior distribution on locations should be considered.

Let $L_c$ be a bivariate random variable describing the centre of the population. Let $L_{i, t}$ be a bivariate random variable describing the location of fly $i$ at time $t$. It seems natural to assume that $\mathrm E (L_{i, t} \mid L_c) = L_c$, for any $(i, t)$. This model assumes that the centre of the population does not move over time. Further, we can specify that $(L_{i, t} \perp \!\!\! \perp  L_{i', t'}) \mid L_c$, for $(i, t) \neq (i', t')$. I.e., conditional on the centre of the population, the fly locations provide no information about each other. This gives the computational advantage that we do not need to track flies locations across time. At each time period, they scatter independently. 

The benefit of these assumptions is that prior distributions can be set on the parameters governing $L_c$ and $L_{i, t} \mid L_c$ separately. The prior distribution on $L_{i, t}$ describes the distribution of fly dispersals. Information on this quantity, for a given species, will often be available in scientific literature.

### Probability of capture (likelihood)

Recall from above that the number of captures (and therefore the data for this model) at time point $t$ is written as $y_t$, for $t \in \{1, \ldots, T\}$. Recall that we assume that the trap locations are each fixed and known with certainty. Further, we denote the probability that fly $i$ is caught in trap $k$ at time $t$ is $p(c \mid d_{i, k, t})$ where $d_{i,k,t}$ is the distance between fly $i$ and trap $k$ at time $t$. Then, the probability that fly $i$ is caught at any trap is simply 
$$
p_{i, t} := 1 - \prod_{k=1}^K(1 - p(c \mid d_{i, k, t})).
$$
I.e., it is the probability that the fly is caught in at least one trap.

Going further, the probability that any fly (out of $N_t$ flies) is caught at any trap is
$$
p_t := 1 - \prod_{t=1}^{N_t} (1 - p_{i,t}).
$$
Therefore, conditional on $\mathbf L_t$ and $N_t$, we can define
$$
y_t = \begin{cases} 1 & \text{one or more flies caught at time} ~t \\ 0 & \text{otherwise.} \end{cases}
$$
For each time point $t$, $y_t$ has the Bernoulli distribution with mean $p_t$.

The probability of capture function, given distance (namely $p(c \mid d)$) should be based on prior analysis of release-recapture data, already discussed, and may be either deterministic or random. For example, we might regress captures on distance, from release-recapture data, and allow coefficients to vary randomly. Then, the posteriors would form the prior distributions for the present model. 

A few things should be noted here. Firstly, $y_t$ is not the number of captures per se, but rather is binary as defined above. This simplification can be made because we are only interested in the case where no flies are detected. This is because the primary application of the model is to evaluate and derive zero-catch criteria. To extend the model to the case where we observe non-zero captures, we can simply define $y_t$ to be the sum of Bernoulli trials for $i \in \{1, \ldots, N_t\}$, each with mean $p_{i,t}$.

Secondly, this model of captures takes for granted the common assumption that there is no interference between traps. This assumption is essentially that the probability that a fly is captured at a given trap is not affected by the presence of other traps. In some cases, this may cause us to overestimate the probability that a fly will be captured at a trap. Adding an extra trap slightly lowers the probability a fly will be captured in any other traps. This is because capture is an "absorbing state" for flies -- they cannot be captured anywhere else after they have been captured once.

This is not likely to be a significant issue in practice. The reason for this is that $p(c \mid d)$ is typically estimated to decrease quickly as a function of distance. This is because traps are generally ineffective as attractants. Therefore, given a single fly location, it is typical that $p(c \mid d_{i, k, t})$ is very small for all but at most one trap. In other words, given any location for a single fly, there will typically be at most one trap such that this fly is close enough to have a significant probability of being captured in that trap. Therefore, the effect of trap interference can be discounted. High-distance traps have capture probability too low to significantly affect capture probability for low-distance traps. And low-distance do not affect high-distance traps, because the probability of capture is already extremely close to zero for the latter. 

Thirdly, the reader should note that it is assumed that this is homogenous across time. I.e., the population size $N_t$ and locations of flies $\mathbf L_t$ tell us everything we can know about whether a fly is captured at time $t$. As such, it is assumed implicitly that temperature does not directly affect fly behaviour. This is a strong assumption, against which there is some evidence (see @bali2021).

Finally, a key limitation of the method proposed here is that, in general, it will not give prior and posterior densities for the probability of eradication. In general, it would be desirable to quantify uncertainty about the result. In future work, reparameterisations of the model should be investigated to allow for such an extension.

## Posterior inference

The statistical problem at hand is to infer the probability of eradication, given that no flies have been detected. In the notation defined above, this is $\Pr(N_T = 0 \mid \mathbf y = \mathbf 0_T)$, where $T$ is some threshold. When $T$ is the zero-catch criteria, this gives us the posterior probability that the zero-catch criteria declares eradications *too early* (i.e. before the suspected pest population has been successfully eradicated). As such, the core statistical problem is to infer the posterior distribution of $N_T$.

The above model can also be used to propose new zero-catch criteria. For example, the decision-maker might set a risk-appetite $\alpha$ close to zero, such that a zero-catch criterion is considered reasonable if it ensures a posterior probability of eradication of at least $1-\alpha$. Then, we simply need to find the smallest $T$ such that $\Pr(N_T = 0 \mid \mathbf y = \mathbf 0_T) \geq 1-\alpha$. This provides a transparent, and rigorously defined, model-based rule of thumb for declaring eradication. 

## Conclusion

In this chapter, I have laid out a basic framework for model-based evaluation and proposal of zero-catch criteria. This provides a general-purpose statistical methodology to support tephritid fruit fly outbreak monitoring. Notably, however, the prior distributions and the likelihood were not specified precisely. In the next chapter, a case study is performed to illustrate the use of the model for a simulated case.

