# Conclusion

There are two main contributions of the present work. The first is a novel method for quantitatively studying zero-trap criteria for tephritid fruit fly outbreaks. This method is primarily composed of a Bayesian model of fly populations, which jointly models the population size, locations and monitoring process of an incipient population of an invasive fly species. Though simple, and limited in important ways, the model is intuitive, and has parameters which are easily interpreted. The second contribution is an in-depth application of the model to a hypothetical outbreak of Medfly. The case study illustrates use of the method for evaluating zero-catch criteria. 

The findings are consequential for both future research and policy. With respect to the former, the project highlights a number of potentially fruitful avenues for research. Firstly, we might fit the model to real observed data of outbreaks, rather than hypothetical survey records. This may help us to learn about fly population dynamics, as well as help us to infer absence of possible low-lying remnant populations. Secondly, the model developed in chapter 3 can be applied to situations involving fruit fly species other than Medfly, and even other insect genera. For example, the model may be useful for monitoring control of the Aedes aegypti mosquito, a major vector of both Dengue and yellow fever, as this insect has also been the subject of the release-recapture studies that were used in the analysis of Medfly above (see, e.g., @russell2005mark).

As for policy, the results of the case study in chapter 4 have potentially significant implications for regulatory decision making in Medfly biosecurity. In this hypothetical scenario, the model finds that the probability of eradication is less than 50% at the time of pest reinstatement, under the existing rule-of-thumb eradication declaration date. Further, the time to 95% probability of eradication is nearly three times later than the rule-of-thumb date. If these results are correct, then using the rule-of-thumb may lead the regulator to mistakenly declare eradication, thus allowing an incipient population to become established at small but stable levels. Once established, they may give rise to intermittent outbreaks (i.e. "flare-ups"). Such events impose significant costs to producers and governments, whether due to lost crops or sales, in the case of producers, or material resources used to eradicate, in the case of governments.