---
title: "Time to eradication analysis"
author: "CM"
date: "09/05/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lubridate)
```

# What this document is about

This document contains code for finding the first time with >95% probability of eradication. There is a special purpose algorithm for doing this.

# Simulation code

```{r echo=F}

# General surveillance
grid_size = 4
general_grid_1d = seq(-grid_size / 2, grid_size / 2) * 400
general_grid = expand.grid(general_grid_1d, general_grid_1d)
general_traps = as.matrix(general_grid)

d = 200 / sqrt(2)
supp_grid_1d = seq(-d, d, length.out = 4)
supp_traps = expand.grid(supp_grid_1d, supp_grid_1d)
all_traps = rbind(general_traps, supp_traps)

# Plot traps as a check
par(pty = 's')
plot(all_traps)
plotrix::draw.circle(0, 0, radius=200)
par(pty = 'm')

norm = function(x) sqrt(sum(x^2))

pr_fn_ms = function(d) 0.4702111 * d ^(-1.37)
pr_fn_lg = function(d) exp(-2.66076 - 0.01109 * d) / 2

# Get probability of capture as a function of distance
# Inputs
#   d (float): distance btw fly and trap
#   pr_fn (function): one of pr_fn_ms or pr_fn_lg
#   threshold (float): lowest distance for which we will compute the pr_fn function.
pr_cap = function(d, pr_fn, threshold=1) {
  # Probability a single fly IS captured at 1 trap in 1 time period
  # We divide distance by 1000 to rescale to metre scale
  prob = function(distance) 1 - (1 - pr_fn(distance))^(1/4)

  ifelse(d <= threshold, prob(threshold), prob(d))
}

# Function to simulate Medfly population dynamics
# Inputs
#   n_periods (int): number of weeks
#   growth_params (list(mu=numeric(n_periods), sd=numeric(n_periods))): 
#     weekly growth mean and sd
draw_N = function(n_periods, growth_params) {
  N = growth_rates = numeric(n_periods)
  
  # Draw growth rates
  growth_rates[2:n_periods] = rnorm(n_periods-1, growth_params$mu, growth_params$sd)
  
  # Draw number of flies at t_1
  N[1] = rgeom(1, 1/20) 
  
  # Draw the no. of flies at t_2, t_3, ...
  for (t in 2:n_periods) {
    N[t] = rpois(1, N[t-1] * exp(growth_rates[t]))
  }
  
  return(N)
}

# Function to draw a single simulation of a typical scenario
# Inputs
#   n_periods (int): number of weeks
#   growth_params (list(mu=numeric(n_periods), sd=numeric(n_periods))): 
#     weekly growth mean and sd
# Output
#   N (numeric(n_periods)): population size at each (weekly) time point

sim_erad = function(n_periods, growth_params) {
  # Initialise capture data
  y = numeric(n_periods)
  
  # Draw the population size fore each time point
  N = draw_N(n_periods, growth_params)
  
  # Draw location and individual dispersals/deviations
  L = rnorm(2, sd = 160)
  
  # Init variable storing time of first detection
  first_detection = Inf
  
  # Capture probabilities
  for (t in 1:n_periods) {
    # Exit early if N[1] == 0 because we already know there will be zero
    # detections.
    if (N[t] == 0) break
    
    # Check whether we're in a supplementary or general period
    n_traps = ifelse(t < 7, nrow(all_traps), nrow(general_traps))
  
    # Draw dispersals
    fly_locs = L + matrix(rnorm(2*N[t], sd=12.5), nrow=2)
    
    # Probability of no captures at t (log scale)
    pr_no_caps_ln = 0
    
    for (k in 1:n_traps) {
      # Distance between trap k and each fly
      distances = sqrt(colSums((fly_locs - unlist(all_traps[k,]))^2))
      
      # Update probability of no captures
      pr_no_caps_ln = pr_no_caps_ln + sum(log(1-pr_cap(distances, pr_fn_ms)))
    }
    
    #y_t = 1 iff no flies are captured
    y[t] = rbinom(1, 1, exp(pr_no_caps_ln))
    
    # Check if we caught a fly
    if (!y[t]) {
      first_detection = t
      break
    }
  }
  
  # Return population sizes and an indicator for acceptance
  return(c(first_detection, N))
}

# Draw 1e4 posterior samples
sim_post = function(n_iter, n_periods, growth_params) {
  posterior_N = matrix(NA, n_iter * 10, n_periods + 1)
  count_success = count_all = 0
  
  pb = progress::progress_bar$new(total=n_iter)
  
  while (count_success < n_iter) {
    new = sim_erad(n_periods, growth_params)
    
    count_all = count_all + 1
    
    # Check if there are no detections
    if (is.infinite(new[1])) {
      count_success = count_success + 1
      pb$tick()
    }
    
    posterior_N[count_all,] = new
  
  }
  
  print(paste('Success rate:', count_success / count_all))
  
  posterior_N_df = as.data.frame(na.omit(posterior_N))
  
  colnames(posterior_N_df) = c('first_detection', paste0('N_', 1:n_periods))
  
  return(posterior_N_df)
}

```

# Growth priors



```{r echo=F}

a = -0.000386 
b = 0.0279 
c = -0.374

# Adelaide weather

min = read.csv('results/adelaide_weather/adelaide_weather_min.csv') 
max = read.csv('results/adelaide_weather/adelaide_weather_max.csv')

growth_df = min %>% 
  left_join(max, by = c('Year', 'Month', 'Day')) %>%
  filter(Year %in% 2020:2021) %>% 
  rename(min = Minimum.temperature..Degree.C.,
         max = Maximum.temperature..Degree.C.) %>%
  mutate(date = make_date(Year, Month, Day)) %>%
  mutate(temp = (min + max) / 2) %>%
  select(date, temp) %>%
  mutate(r = a * temp^2 + b * temp + c) 


temp_fn = function(x) a * x^2 + b * x + c
curve(temp_fn(x), 8, 30)

# Kean & Stringer growth function
n_periods = 36

start_date = make_date(2020, 11, 1)
end_date = start_date + 7 * n_periods - 1
start_ind = which(growth_df$date == start_date)
end_ind = start_ind + 7 * n_periods - 1


# Get the parameters corresponding to the months
mu = matrix(growth_df$r[start_ind:end_ind], nrow=7)
sd = 0.07

growth_params = data.frame(mu_r = colSums(mu),
                           sd_r = sd * 7)
```

### Case study/proof of concept

```{r}
if (FALSE) {
  n_iter = 1e4
  
  # Draw posteriors
  post_draws = sim_post(n_iter, n_periods, growth_params)
  
  prob_erad_prior = colMeans(post_draws[, -1] == 0)
  
  prob_erad_post = numeric(n_periods)
  
  for (t in 1:n_periods) {
    post_index = which(post_draws$first_detection > t)
    prob_erad_post[t] = mean(post_draws[post_index, t+1] == 0)
  }
  
  time_to_erad_result_nov = data.frame(prior_probs = colMeans(post_draws[,-1] == 0), 
                                        post_probs = prob_erad_post)
  
  saveRDS(time_to_erad_result_nov,
          'results/pfa_criteria_evaluation/time_to_erad_result_v2.RDS')
}

# [1] "Success rate: 0.217004470292088"                                                                                
time_to_erad_result_nov = readRDS('results/pfa_criteria_evaluation/time_to_erad_result_v2.RDS')

dates = seq(start_date, end_date, 7)
pfa_date = start_date + 7*12 - 1

line_data = data.frame(x = c(pfa_date, dates[35]),
                       name = c('PFA reinstatement date',
                                'First week with posterior prob > 95%'))

labels = data.frame(x = c(pfa_date, dates[35] - 28), 
                    y = c(0.1, 0.5),
                    text = c('PFA reinstatement date',
                             'First week with posterior \n prob >95%'))

time_to_erad_result_nov %>%
  mutate(date = dates) %>%
  pivot_longer(cols = c(prior_probs, post_probs)) %>%
  ggplot() +
    geom_line(aes(date, value, col = name), 
              size = 2, lineend = 'round') +
    xlab('Date') +
    ylab('Probability of eradication') +
    labs(col = '') +
    geom_vline(aes(xintercept = x), line_data, size=2) +
    scale_color_hue(labels = c('Posterior', 'Prior')) +
    scale_x_date(date_breaks = '1 month', date_labels = '%B', date_minor_breaks = '1 month') +
    scale_y_continuous(limits = 0:1) +
    ggtitle('Prior vs. posterior probability of eradication over 36 weeks') +
    geom_label(aes(x, y, label = text), data = labels) +
    theme_bw()

ggsave('results/pfa_criteria_evaluation/prior_vs_post_plot.png')

# Note: add a label for the first week
# Make the X axis "weeks since outbreak"
```


```{r}
# Check growth
((replicate(50, draw_N(36, growth_params))) + 0.1) %>% matplot(type = 'l', log = 'y')
draw_N(36, growth_params)
```

